version: '3'
services:
  kongming:
    image: "server:v2"
    hostname: kongming
    networks:
      - server
    volumes:
      - /home/caieleven/accessWEB/:/accessWEB/
    # command: /bin/bash
    tty: true

  laptop:
    image: "server:v2"
    hostname: laptop
    networks:
      - server
    volumes:
      - /home/caieleven/accessWEB/:/accessWEB/ 
    # command: /bin/bash
    tty: true

networks:
  server:
